### PR TITLE
Addition of composer

### PR DESCRIPTION
**Pull request by djoos**
Hi @popthestack,

as requested (quite) a while ago in pzb/requestcore (see: https://github.com/pzb/requestcore/pull/2)...

Thanks in advance for your feedback!

Kind regards,
David

### CODE REVIEW

**Comment by popthestack** [comment]
Thanks!

**Comment by popthestack** [comment]
I've now added the project on packagist.

**Comment by djoos** [comment]
Great!

Any chance you could push out a new (1.2.0) release?

Thanks in advance!

**Comment by popthestack** [comment]
Done!

**Comment by djoos** [comment]
Is it possible you haven't pushed the tags to the origin yet? Can't seem to spot the release [here](https://github.com/popthestack/requestcore/releases)...

Thanks in advance!

**Comment by popthestack** [comment]
Oops. I have shame.

Shame

Done.

**Comment by djoos** [comment]
lol

...no worries, thanks!

:+1:

**Pull request merged**
